---
name: CI

on:
  pull_request:

jobs:

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: /
          VALIDATE_ANSIBLE: false

  molecule:
    needs: lint
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.x"

      - name: Install Tox
        run: |
          pip3 install tox

      - name: Run Molecule tests
        run: tox
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
